image: node:8.10

stages:
  - deploy

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
  - npm install -g serverless

deploy_staging:
  stage: deploy
  script:
    - serverless create_domain
    - serverless deploy
  variables:
    DOMAIN: "stag.gowind.tk"
    STAGE: "stag"
  only:
    refs:
      - develop

deploy_production:
  stage: deploy
  script:
    - serverless create_domain
    - serverless deploy
  variables:
    DOMAIN: "gowind.tk"
    STAGE: "prod"
  only:
    refs:
      - release
