stages:
 - deploy

before_script:
 - curl -o- -L https://yarnpkg.com/install.sh | bash
 - export PATH="$HOME/.yarn/bin:$PATH"
 - yarn install
 - npm install -g serverless

deploy:
 stage: deploy
 script:
  - bash deploy.sh production
