image: node:8.10

stages:
  - deploy

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
  - npm install -g serverless

deploy_staging:
  stage: deploy
  script:
    - yarn deploy
  variables:
    NODE_ENV: "staging"
    DOMAIN: "gowind.tk"
  only: 
    refs:
      - develop

deploy_production:
  stage: deploy
  script:
    - yarn deploy
  variables:
    NODE_ENV: "production"
    DOMAIN: "gowind.tk"
  only: 
    refs:
      - release
