image: node:8.10

cache:
  paths:
    - node_modules/
    
stages:
  - test
  - deploy

before_script:
  - npm install -g serverless
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install

lint:
  stage: test
  script:
    - yarn lint

test:
  stage: test
  script:
    - yarn test

deploy_staging:
  stage: deploy
  script:
    - yarn deploy
  variables:
    STAGE: "stag"
    DOMAIN: "stag.gowind.tk"
    API_DOMAIN: "stag.api.gowind.tk"
  only:
    refs:
      - develop

deploy_production:
  stage: deploy
  script:
    - yarn deploy
  variables:
    STAGE: "prod"
    DOMAIN: "gowind.tk"
    API-DOMAIN: "api.gowind.tk"
  only:
    refs:
      - release
