service: ssr-react-next

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.secrets.NODE_ENV}
  region: ap-southeast-1
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}

plugins:
  - serverless-nextjs-plugin
  - serverless-apigw-binary
  - serverless-domain-manager
  - serverless-offline

custom:
  secrets: ${file(secrets.json)}
  serverless-nextjs:
    nextConfigDir: "./"
    pageConfig:
      b_detail:
        events:
          - http:
              path: b/{id}
              request:
                parameters:
                  paths:
                    id: true
  apigwBinary:
    types:
      - "*/*"
  customDomain:
    domainName: ${self:custom.secrets.DOMAIN}
    basePath: ""
    stage: ${self:custom.secrets.NODE_ENV}
    createRoute53Record: true
  # endpointType: 'regional'
  # if the ACM certificate is created in a region except for `'us-east-1'` you need `endpointType: 'regional'`

package:
  exclude:
    - ./**
